import { useState, useEffect } from "react";
import DashboardLayout, { principalNav } from "@/components/dashboard/DashboardLayout";
import { Button } from "@/components/ui/button";
import { BarChart3, Download, Calendar, TrendingUp, FileDown, RefreshCw, Users, CheckSquare } from "lucide-react";
import { collection, getDocs, query, where } from "firebase/firestore";
import { db } from "@/integrations/firebase/config";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { downloadAsPDF, downloadAsWord } from "@/lib/reportExport";

const PrincipalReports = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState<string | null>(null);

  // Raw data
  const [meetings, setMeetings] = useState<any[]>([]);
  const [tasks, setTasks] = useState<any[]>([]);
  const [users, setUsers] = useState<any[]>([]);

  useEffect(() => {
    if (!user?.id) return;
    const load = async () => {
      setLoading(true);
      try {
        const [mSnap, tSnap, uSnap] = await Promise.all([
          getDocs(collection(db, "meetings")),
          getDocs(collection(db, "tasks")),
          getDocs(collection(db, "users")),
        ]);
        const allMeetings = mSnap.docs.map(d => ({ id: d.id, ...d.data() })) as any[];
        setMeetings(allMeetings.filter((m: any) =>
          m.createdBy === user.id || m.participants?.includes(user.id)
        ));
        setTasks(tSnap.docs.map(d => ({ id: d.id, ...d.data() })) as any[]);
        setUsers(uSnap.docs.map(d => ({ id: d.id, ...d.data() })) as any[]);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [user?.id]);

  // ── Stats ──────────────────────────────────────────────────────────────────
  const totalMeetings = meetings.length;
  const completedMeetings = meetings.filter(m => m.status === "completed").length;
  const pendingMeetings = meetings.filter(m => m.status === "scheduled" || m.status === "in_progress").length;

  const myMeetingIds = new Set(meetings.map(m => m.id));
  const myTasks = tasks.filter(t => myMeetingIds.has(t.meetingId) || t.assignedBy === user?.id);
  const totalTasks = myTasks.filter(t => t.status !== "suggested").length;
  const completedTasks = myTasks.filter(t => t.status === "completed").length;
  const pendingTasks = myTasks.filter(t => t.status === "pending").length;
  const inProgressTasks = myTasks.filter(t => t.status === "in_progress").length;
  const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

  const userName = (id: string) => users.find(u => u.id === id)?.name || id;
  const fmtDate = (ts: any) => ts?.toDate?.().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) ?? "—";

  // ── Report builders ────────────────────────────────────────────────────────
  const buildMeetingSummary = () => {
    const rows = meetings.map((m, i) =>
      `| ${i + 1} | ${m.title} | ${fmtDate(m.scheduledAt)} | ${m.status} | ${(m.participants?.length ?? 0) + 1} | ${m.venue || "—"} |`
    ).join("\n");

    return `# Meeting Summary Report

---

## Overview

*   **Total Meetings:** ${totalMeetings}
*   **Completed:** ${completedMeetings}
*   **Pending / In Progress:** ${pendingMeetings}
*   **Report Generated:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

---

## Meeting Details

| # | Title | Date | Status | Participants | Venue |
| :-- | :--- | :--- | :--- | :--- | :--- |
${rows}

---

*Generated by MeetSync*`;
  };

  const buildTaskReport = () => {
    const activeTasks = myTasks.filter(t => t.status !== "suggested");
    const rows = activeTasks.map((t, i) => {
      const due = t.dueDate || t.suggestedDueDate;
      return `| ${i + 1} | ${t.title || t.description} | ${userName(t.assignedTo)} | ${t.priority} | ${t.status} | ${fmtDate(due)} |`;
    }).join("\n");

    return `# Task Completion Report

---

## Summary

*   **Total Tasks:** ${totalTasks}
*   **Completed:** ${completedTasks}
*   **In Progress:** ${inProgressTasks}
*   **Pending:** ${pendingTasks}
*   **Completion Rate:** ${completionRate}%
*   **Report Generated:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

---

## Task Details

| # | Task | Assigned To | Priority | Status | Due Date |
| :-- | :--- | :--- | :--- | :--- | :--- |
${rows}

---

*Generated by MeetSync*`;
  };

  const buildUserActivityReport = () => {
    const activeUsers = users.filter(u => !u.isDeleted);
    const rows = activeUsers.map((u, i) => {
      const participated = meetings.filter(m => m.participants?.includes(u.id) || m.createdBy === u.id).length;
      const assigned = myTasks.filter(t => t.assignedTo === u.id && t.status !== "suggested").length;
      const done = myTasks.filter(t => t.assignedTo === u.id && t.status === "completed").length;
      const rate = assigned > 0 ? Math.round((done / assigned) * 100) : 0;
      return `| ${i + 1} | ${u.name} | ${u.role} | ${u.designation || "—"} | ${participated} | ${assigned} | ${done} | ${rate}% |`;
    }).join("\n");

    return `# User Activity Report

---

## Summary

*   **Total Users:** ${activeUsers.length}
*   **Report Generated:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

---

## User Details

| # | Name | Role | Designation | Meetings | Tasks Assigned | Tasks Completed | Rate |
| :-- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
${rows}

---

*Generated by MeetSync*`;
  };

  const buildMonthlyReport = () => {
    // Group meetings by month
    const byMonth: Record<string, any[]> = {};
    meetings.forEach(m => {
      const d = m.scheduledAt?.toDate?.();
      if (!d) return;
      const key = d.toLocaleDateString("en-US", { month: "long", year: "numeric" });
      if (!byMonth[key]) byMonth[key] = [];
      byMonth[key].push(m);
    });

    const rows = Object.entries(byMonth).map(([month, ms]) => {
      const done = ms.filter(m => m.status === "completed").length;
      const tasksDone = myTasks.filter(t => {
        const d = t.createdAt?.toDate?.();
        if (!d) return false;
        return d.toLocaleDateString("en-US", { month: "long", year: "numeric" }) === month && t.status === "completed";
      }).length;
      return `| ${month} | ${ms.length} | ${done} | ${tasksDone} |`;
    }).join("\n");

    return `# Monthly Activity Report

---

## Summary

*   **Period Covered:** All time
*   **Total Months:** ${Object.keys(byMonth).length}
*   **Report Generated:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

---

## Monthly Breakdown

| Month | Meetings Held | Meetings Completed | Tasks Completed |
| :--- | :--- | :--- | :--- |
${rows}

---

*Generated by MeetSync*`;
  };

  // ── Generate handler ───────────────────────────────────────────────────────
  const generate = async (type: string, format: "pdf" | "word") => {
    setGenerating(`${type}-${format}`);
    try {
      let report = "";
      let title = "";
      if (type === "meeting") { report = buildMeetingSummary(); title = "Meeting_Summary_Report"; }
      else if (type === "task") { report = buildTaskReport(); title = "Task_Completion_Report"; }
      else if (type === "user") { report = buildUserActivityReport(); title = "User_Activity_Report"; }
      else if (type === "monthly") { report = buildMonthlyReport(); title = "Monthly_Activity_Report"; }

      if (format === "pdf") downloadAsPDF(report, title);
      else await downloadAsWord(report, title);

      toast({ title: "Downloaded", description: `${title.replace(/_/g, " ")} exported as ${format.toUpperCase()}` });
    } catch (e) {
      toast({ title: "Error", description: "Failed to generate report", variant: "destructive" });
    } finally {
      setGenerating(null);
    }
  };

  // ── UI ─────────────────────────────────────────────────────────────────────
  const reportCards = [
    {
      id: "meeting",
      title: "Meeting Summary Report",
      desc: "All meetings, attendance, status and venues",
      icon: <Calendar className="w-6 h-6 text-blue-600" />,
      bg: "bg-blue-100",
    },
    {
      id: "task",
      title: "Task Completion Report",
      desc: "Task status, assignees, priorities and due dates",
      icon: <CheckSquare className="w-6 h-6 text-green-600" />,
      bg: "bg-green-100",
    },
    {
      id: "user",
      title: "User Activity Report",
      desc: "Participation and task completion per user",
      icon: <Users className="w-6 h-6 text-purple-600" />,
      bg: "bg-purple-100",
    },
    {
      id: "monthly",
      title: "Monthly Activity Report",
      desc: "Month-by-month breakdown of meetings and tasks",
      icon: <TrendingUp className="w-6 h-6 text-orange-600" />,
      bg: "bg-orange-100",
    },
  ];

  return (
    <DashboardLayout role="Principal Dashboard" navItems={principalNav}>
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-display font-bold text-foreground">Reports</h1>
          <p className="text-muted-foreground">Generate and download institutional reports</p>
        </div>
        <Button variant="outline" size="sm" onClick={() => window.location.reload()}>
          <RefreshCw className="w-4 h-4 mr-1" /> Refresh
        </Button>
      </div>

      {/* Stats bar */}
      {!loading && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-8">
          {[
            { label: "Total Meetings", value: totalMeetings, color: "text-blue-600" },
            { label: "Completed Meetings", value: completedMeetings, color: "text-green-600" },
            { label: "Total Tasks", value: totalTasks, color: "text-purple-600" },
            { label: "Task Completion", value: `${completionRate}%`, color: "text-orange-600" },
          ].map(s => (
            <div key={s.label} className="bg-card rounded-xl p-4 border border-border">
              <p className="text-xs text-muted-foreground">{s.label}</p>
              <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            </div>
          ))}
        </div>
      )}

      {loading ? (
        <div className="flex items-center justify-center min-h-[300px]">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600" />
        </div>
      ) : (
        <div className="grid md:grid-cols-2 gap-6">
          {reportCards.map(card => (
            <div key={card.id} className="bg-card rounded-xl p-6 border border-border shadow-card">
              <div className="flex items-start gap-4 mb-4">
                <div className={`w-12 h-12 rounded-lg ${card.bg} flex items-center justify-center shrink-0`}>
                  {card.icon}
                </div>
                <div>
                  <h3 className="text-base font-semibold text-foreground">{card.title}</h3>
                  <p className="text-sm text-muted-foreground mt-0.5">{card.desc}</p>
                </div>
              </div>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  className="flex-1"
                  disabled={!!generating}
                  onClick={() => generate(card.id, "pdf")}
                >
                  <FileDown className="w-4 h-4 mr-1" />
                  {generating === `${card.id}-pdf` ? "Generating..." : "PDF"}
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  className="flex-1"
                  disabled={!!generating}
                  onClick={() => generate(card.id, "word")}
                >
                  <Download className="w-4 h-4 mr-1" />
                  {generating === `${card.id}-word` ? "Generating..." : "Word"}
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </DashboardLayout>
  );
};

export default PrincipalReports;
